CREATE TABLE `COMMON_CODE` (
  `COMM_CODE` VARCHAR(20) NOT NULL COMMENT '공통코드',
  `COMM_CODE_NAME` VARCHAR(50) NOT NULL COMMENT '공통코드명',
  `DESCRIPTION` VARCHAR(300) DEFAULT NULL COMMENT '설명',
  `USE_YN`  CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
  `REG_YMDT` DATETIME COMMENT '등록일시',  
  PRIMARY KEY (`COMM_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `COMMON_CATEGORIZE_CODE` (
  `COMM_CODE` VARCHAR(20) NOT NULL COMMENT '공통코드',  
  `COMM_CAT_CODE` VARCHAR(20) NOT NULL COMMENT '공통분류코드',
  `COMM_CAT_CODE_NAME` VARCHAR(50) NOT NULL COMMENT '공통분류코드명',  
  `DESCRIPTION` VARCHAR(300) DEFAULT NULL COMMENT '설명',
  `USE_YN`  CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
  `REG_YMDT` DATETIME COMMENT '등록일시',  
  PRIMARY KEY (`COMM_CODE`,`COMM_CAT_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;