CREATE TABLE `COMMON_CODE` (
  `COMM_CODE` VARCHAR(20) NOT NULL COMMENT '공통코드',
  `COMM_CODE_NAME` VARCHAR(50) NOT NULL COMMENT '공통코드명',
  `DESCRIPTION` VARCHAR(300) DEFAULT NULL COMMENT '설명',
  `USE_YN`  CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
  `REG_ID` VARCHAR(20) DEFAULT NULL COMMENT '등록ID',
  `REG_YMDT` DATETIME COMMENT '등록일시',  
  PRIMARY KEY (`COMM_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `COMMON_CATEGORIZE_CODE` (
  `COMM_CODE` VARCHAR(20) NOT NULL COMMENT '공통코드',  
  `COMM_CAT_CODE` VARCHAR(20) NOT NULL COMMENT '공통분류코드',
  `COMM_CAT_CODE_NAME` VARCHAR(50) NOT NULL COMMENT '공통분류코드명',  
  `DESCRIPTION` VARCHAR(300) DEFAULT NULL COMMENT '설명',
  `USE_YN`  CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
  `REG_ID` VARCHAR(20) DEFAULT NULL COMMENT '등록ID',
  `REG_YMDT` DATETIME COMMENT '등록일시',  
  PRIMARY KEY (`COMM_CODE`,`COMM_CAT_CODE`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

 CREATE TABLE `USERS` (
  `USERNAME` VARCHAR(100) NOT NULL COMMENT '사용자명',
  `ENCODED_PASSWORD` VARCHAR(255) DEFAULT NULL COMMENT '비밀번호',
  PRIMARY KEY (`USERNAME`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `PAYMENT_WITHDRAW_DETAILED_LIST` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '순번',
  `COMM_CODE` VARCHAR(20) NOT NULL COMMENT '구분코드',
  `COMM_CAT_CODE` VARCHAR(20) NOT NULL COMMENT '상세구분코드',
  `CONTENT` VARCHAR(200) NOT NULL COMMENT '내용',
  `MEMO` VARCHAR(200) DEFAULT NULL COMMENT '메모',
  `AMOUNT` DOUBLE UNSIGNED NOT NULL COMMENT '금액',
  `USE_YMD` DATE NULL COMMENT '사용일',
  `REG_ID`  VARCHAR(20) NULL COMMENT '등록ID',
  `REG_YMDT` DATETIME NULL COMMENT '등록일시',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;